// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransitSurveyAzure.Data;

#nullable disable

namespace TransitSurveyAzure.Migrations
{
    [DbContext(typeof(SurveyDbContext))]
    [Migration("20250312211758_InitialWithSurveyTable")]
    partial class InitialWithSurveyTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransitSurveyAzure.Models.MetroResidentSurveyResponses", b =>
                {
                    b.Property<int>("zipcode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("zipcode"));

                    b.Property<double>("com_not_car")
                        .HasColumnType("float");

                    b.Property<byte>("num_response")
                        .HasColumnType("tinyint");

                    b.Property<double>("pub_access")
                        .HasColumnType("float");

                    b.HasKey("zipcode");

                    b.ToTable("Metro_Resident_Survey_Responses_result");
                });
#pragma warning restore 612, 618
        }
    }
}
